export const MENU_CATEGORIES = [
    { id: 'accompaniments', name: 'Acompanhamentos' },
    { id: 'appetizers', name: 'Entradas' },
    { id: 'main', name: 'Pratos Principais' },
    { id: 'desserts', name: 'Sobremesas' },
    { id: 'drinks', name: 'Bebidas' },
    { id: 'sides', name: 'Acompanhamentos' },
    { id: 'specials', name: 'Especiais' },
    { id: 'vegan', name: 'Vegano' },
    { id: 'gluten-free', name: 'Sem Glúten' },
    { id: 'breakfast', name: 'Café da Manhã' },
    { id: 'snacks', name: 'Lanches' },
    { id: 'salads', name: 'Saladas' },
    { id: 'soups', name: 'Sopas' },
    { id: 'pizzas', name: 'Pizzas' },
    { id: 'burgers', name: 'Hambúrgueres' },
    { id: 'pastas', name: 'Massas' },
    { id: 'seafood', name: 'Frutos do Mar' },
    { id: 'grills', name: 'Grelhados' },
    { id: 'international', name: 'Internacional' },
    { id: 'kids', name: 'Menu Infantil' },
    { id: 'healthy', name: 'Saudável' },
    { id: 'snacks2', name: 'Petiscos' },
    { id: 'cocktails', name: 'Coquetéis' },
    { id: 'smoothies', name: 'Smoothies' },
    { id: 'teas', name: 'Chás' },
    { id: 'coffees', name: 'Cafés' },
    { id: 'wines', name: 'Vinhos' },
    { id: 'beers', name: 'Cervejas' },
    { id: 'spirits', name: 'Destilados' },
    { id: 'addOns', name: 'Adicionais' },
];